import 'dart:io';

import 'package:compendium_core/src/privacy/data_classification.dart';
import 'package:compendium_core/src/privacy/field_registry.dart';
import 'package:compendium_core/src/sync/sync_record_kind.dart';
import 'package:compendium_core/src/sync/wire_mapping.dart';

const _outputPath = 'lib/src/sync/generated_sync_allow_list.dart';

void main(List<String> args) {
  final output = renderSyncAllowList();
  final check = args.contains('--check');
  final path = args.firstWhere(
    (arg) => arg != '--check',
    orElse: _defaultOutputPath,
  );
  final file = File(path);
  if (check) {
    if (!file.existsSync() || file.readAsStringSync() != output) {
      stderr.writeln('Generated sync allow-list is stale: ${file.path}');
      exitCode = 1;
    }

    return;
  }
  file.writeAsStringSync(output);
  stdout.writeln('Generated sync allow-list in ${file.path}');
}

String _defaultOutputPath() =>
    Directory('packages/compendium_core').existsSync()
    ? 'packages/compendium_core/$_outputPath'
    : _outputPath;

String renderSyncAllowList() {
  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('// Generated by tool/generate_sync_allow_list.dart.')
    ..writeln()
    ..writeln("import 'sync_record_kind.dart';")
    ..writeln()
    ..writeln(
      '/// Shareable wire paths derived from the structural mapping and privacy '
      'registries.',
    )
    ..writeln(
      'const Map<SyncRecordKind, Set<String>> generatedShareableWirePaths = {',
    );

  for (final kind in SyncRecordKind.values) {
    final paths = <String>{};
    for (final field in syncWireFields[kind]!) {
      if (field.sourceFields.isNotEmpty &&
          field.sourceFields.any(_isShareable)) {
        paths.add(field.path);
        var parent = field.path;
        while (parent.contains('.')) {
          parent = parent.substring(0, parent.lastIndexOf('.'));
          paths.add(parent);
        }
      }
    }
    final sorted = paths.toList()..sort();
    final key = 'SyncRecordKind.${kind.name}';
    if (sorted.length <= 4) {
      buffer.writeln(
        "  $key: {${sorted.map((path) => "'$path'").join(', ')}},",
      );
    } else {
      buffer
        ..writeln('  $key: {')
        ..writeln(sorted.map((path) => "    '$path',").join('\n'))
        ..writeln('  },');
    }
  }
  buffer.writeln('};');
  return buffer.toString();
}

bool _isShareable(String source) {
  final classification = fieldClassifications[source];
  if (classification == null) {
    throw StateError('Mapping references unclassified field: $source');
  }
  return classification.egress == EgressClass.shareable;
}
