import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';

/// The Caller's Compendium brand mark — "Dancers rising from a book".
///
/// Two role-neutral dancers spin up out of an open book; the same illustration
/// is used for every launcher icon (generated by `tools/brand/generate_icons.py`
/// from the SVG sources in `assets/brand/`). To stay pixel-identical to those
/// icons, the in-app reuse points — the navigation-rail mark and the empty-state
/// marks — render those very SVGs via `flutter_svg` rather than re-drawing the
/// art in a [CustomPainter].
///
/// Two rendering modes:
///
/// * **[showTile] = true** — the full-colour illustration on its rounded Soft
///   Dark tile (the app icon). Small sizes (<= 32 px) use the simplified
///   two-dancers "small mark" so it stays legible, mirroring the launcher-icon
///   size policy. Used for the nav-rail brand and the About header.
/// * **[showTile] = false** (default) — the simplified mark as a single-colour
///   silhouette, tinted with [color] (defaults to the muted
///   [ColorScheme.onSurfaceVariant]) so it sits quietly in chrome / empty
///   states.
class BrandMark extends StatelessWidget {
  const BrandMark({
    super.key,
    this.size = 24,
    this.color,
    this.showTile = false,
    this.semanticLabel,
  });

  /// Brand Soft Dark tile colour — the default launcher-icon background and the
  /// Soft Dark scheme surface (`#1E2A38`).
  static const Color brandBackground = Color(0xFF1E2A38);

  /// Lantern amber — the warm accent in the illustration (`#FFB784`).
  static const Color brandForeground = Color(0xFFFFB784);

  // Brand SVG sources (bundled via pubspec `assets/brand/`).
  static const String _fullTileAsset = 'assets/brand/icon.svg';
  static const String _smallTileAsset = 'assets/brand/icon-small.svg';
  static const String _markAsset = 'assets/brand/mark-small.svg';

  /// Below/at this edge length the simplified small mark is used instead of the
  /// full illustration (mirrors the launcher-icon crossover).
  static const double _smallMax = 32;

  /// Edge length of the (square) mark, in logical pixels.
  final double size;

  /// Silhouette tint when [showTile] is false. Defaults to the current theme's
  /// [ColorScheme.onSurfaceVariant]. Ignored when [showTile] is true (the
  /// full-colour illustration is drawn as-authored).
  final Color? color;

  /// Whether to render the full-colour illustration on its rounded brand tile
  /// (the app icon). When false, a single-colour silhouette is drawn instead.
  final bool showTile;

  /// Optional accessibility label. When null the mark is treated as decorative
  /// and excluded from the semantics tree.
  final String? semanticLabel;

  @override
  Widget build(BuildContext context) {
    final Widget graphic;
    if (showTile) {
      final asset = size <= _smallMax ? _smallTileAsset : _fullTileAsset;
      graphic = SvgPicture.asset(asset, width: size, height: size);
    } else {
      final tint = color ?? Theme.of(context).colorScheme.onSurfaceVariant;
      graphic = SvgPicture.asset(
        _markAsset,
        width: size,
        height: size,
        colorFilter: ColorFilter.mode(tint, BlendMode.srcIn),
      );
    }

    final painted = SizedBox.square(dimension: size, child: graphic);

    if (semanticLabel == null) {
      return ExcludeSemantics(child: painted);
    }
    return Semantics(label: semanticLabel, image: true, child: painted);
  }
}
