// Migration tests, per the convention documented on [CompendiumDatabase]:
// every schema migration ships a test that opens a fixture DB captured at the
// previous version and asserts the migration behaves.
//
// Coverage starts at [kMinSupportedSchemaVersion], not at v1. Schema versions
// below the floor were retired (#837, floor since raised past v19) along with
// their `onUpgrade` steps, fixtures and dumps, so there is nothing left to
// migrate from; a below-floor database is refused outright, which
// `schema_floor_test.dart` covers.
//
// Each fixture (`fixtures/vN.sqlite`) is checked in and regenerated by the
// matching `fixtures/generate_vN_fixture.dart` (see those files for the
// scripted procedure). They seed *realistic data*, which is what these tests
// assert on; schema **shape** after migration is covered separately by
// `schema_verification_test.dart`.
//
// Schema *shape* after migration is covered separately by
// `schema_verification_test.dart` (#828); this file covers data semantics.
import 'dart:convert';
import 'dart:io';

import 'package:compendium_core/compendium_core.dart';
import 'package:compendium_core/src/storage/database.dart'
    show VenueProvenanceCompanion, VenuesCompanion;
import 'package:drift/drift.dart' show Value, Variable;
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:sqlite3/sqlite3.dart' as sqlite3;
import 'package:test/test.dart';

import '../test_package_root.dart';
import 'generated/schema.dart';

void main() {
  group('re-homed migration-agnostic tests (from the retired v11 group)', () {
    late Directory dir;
    late String dbPath;

    setUp(() async {
      dir = await Directory.systemTemp.createTemp('compendium_core_mig_v20_');
      dbPath = p.join(dir.path, 'test.sqlite');
      // Copy the checked-in v20 fixture to a temp path (opening mutates it).
      final fixture = File(
        p.join(
          await packageRootPath(),
          'test',
          'storage',
          'fixtures',
          'v20.sqlite',
        ),
      );
      await fixture.copy(dbPath);
    });

    tearDown(() => dir.delete(recursive: true));

    // Re-homed from the retired v11 group (#837, floor raised past v19). The
    // property is not specific to any start version: it asserts that a
    // *failed* derived rebuild is not memoized, so the next `ensureMigrated`
    // retries rather than treating the failure as done. Every supported path
    // to head crosses v22, whose `group_idx` column owes an unconditional
    // rebuild, so the marker this relies on is set from any surviving
    // fixture.
    test('ensureMigrated retries after a failed rebuild', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      final repos = _FailingOnceRepositories(db, contraTaxonomy);

      // First attempt: onUpgrade sets the durable marker, then the rebuild
      // throws. The failure must propagate and NOT be cached.
      await expectLater(repos.ensureMigrated(), throwsA(isA<StateError>()));
      expect(repos.rebuildAttempts, 1);

      // Marker still set — the rebuild did not complete.
      final marker = await db
          .customSelect(
            'SELECT value_json FROM settings WHERE key = ?',
            variables: [Variable.withString(derivedRebuildRequiredKey)],
          )
          .get();
      expect(marker, isNotEmpty);

      // Second attempt: the memo was cleared, so it retries and now succeeds.
      await repos.ensureMigrated();
      expect(repos.rebuildAttempts, 2);
      final cleared = await db
          .customSelect(
            'SELECT value_json FROM settings WHERE key = ?',
            variables: [Variable.withString(derivedRebuildRequiredKey)],
          )
          .get();
      expect(
        cleared,
        isEmpty,
        reason: 'a successful retry must clear the durable marker',
      );

      await db.close();
    });

    // Also re-homed from the retired v11 group (#837, floor raised past v19).
    test('ensureMigrated with both derivedRebuildRequired and sectionRuleVersion '
        'pending performs exactly one rebuild', () async {
      // Guard for the alreadyRebuilt optimisation (#844): when derivedRebuildRequired
      // fires, the rebuild uses current labelForFigure code and already produces
      // correct section values. _recomputeSectionLabelsIfNeeded must not run a
      // second byte-identical pass — it doubles the startup cost for users
      // upgrading from a schema that also sets derivedRebuildRequired.
      //
      // Falsification target: remove the alreadyRebuilt guard in _runMigration
      // (pass alreadyRebuilt: false unconditionally) and this test goes red.
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      final repos = _CountingRepositories(db, contraTaxonomy);

      // v20 fixture needs upgrading → onUpgrade sets derivedRebuildRequiredKey.
      // sectionRuleVersionKey is absent (fresh fixture, never run).
      await repos.ensureMigrated();

      expect(
        repos.rebuildAttempts,
        1,
        reason:
            'derivedRebuildRequired and sectionRuleVersion pending together '
            'must produce exactly one rebuild, not two',
      );

      // Key is written so subsequent opens skip the sweep entirely.
      final key = await db
          .customSelect(
            'SELECT value_json FROM settings WHERE key = ? AND value_json = ?',
            variables: [
              Variable.withString(sectionRuleVersionKey),
              Variable.withString('"$kSectionRuleVersion"'),
            ],
          )
          .get();
      expect(key, isNotEmpty, reason: 'sectionRuleVersionKey must be written');

      await db.close();
    });
  });

  group('purge-corruption repair (#429/#466)', () {
    test(
      'ensureMigrated removes legacy corrupt rows once and marks it done',
      () async {
        final db = CompendiumDatabase(NativeDatabase.memory());
        final repos = CompendiumRepositories(db, contraTaxonomy);
        addTearDown(db.close);

        // A healthy dance + a program whose slot references it, plus a VALID
        // owner->target relatedDance link (both dances present) that the
        // destructive repair sweep must PRESERVE.
        await repos.dances.create(
          Dance(
            id: 'd-target',
            title: 'Target Dance',
            createdAt: DateTime.utc(2026),
            updatedAt: DateTime.utc(2026),
          ),
        );
        await repos.dances.create(
          Dance(
            id: 'd-ok',
            title: 'Good Dance',
            links: [
              DanceLink(
                id: 'l-good',
                kind: LinkKind.relatedDance,
                targetDanceId: 'd-target',
              ),
            ],
            createdAt: DateTime.utc(2026),
            updatedAt: DateTime.utc(2026),
          ),
        );
        await repos.programs.create(
          Program(
            id: 'p1',
            title: 'Set',
            slots: [ProgramSlot(id: 's-ok', position: 0, danceId: 'd-ok')],
            createdAt: DateTime.utc(2026),
            updatedAt: DateTime.utc(2026),
          ),
        );

        // Inject the two row shapes a pre-fix hard purge would have left: a
        // (danceId, text)-both-null slot (#429) and a relatedDance link whose
        // target was SET NULL (#466). Written raw so they bypass the domain
        // guards, exactly like a legacy on-disk database.
        await db.customStatement(
          'INSERT INTO program_slots (id, program_id, position, dance_id, '
          'text, is_alt) VALUES (?, ?, ?, NULL, NULL, 0)',
          ['s-bad', 'p1', 1],
        );
        await db.customStatement(
          'INSERT INTO dance_links (id, dance_id, kind, target_dance_id) '
          'VALUES (?, ?, ?, NULL)',
          ['l-bad', 'd-ok', LinkKind.relatedDance.name],
        );

        await repos.ensureMigrated();

        // The corrupt rows are gone; the healthy rows — including the VALID
        // relatedDance link — survive untouched (the sweep is not over-eager).
        final slots = await db
            .customSelect('SELECT id FROM program_slots ORDER BY id')
            .get();
        expect(slots.map((r) => r.read<String>('id')), ['s-ok']);
        final links = await db
            .customSelect('SELECT id FROM dance_links ORDER BY id')
            .get();
        expect(links.map((r) => r.read<String>('id')), ['l-good']);

        // Loads succeed after the repair, and the valid link still hydrates.
        final programs = await repos.programs.listAll();
        expect(programs.single.slots.single.danceId, 'd-ok');
        final loadedDances = await repos.dances.listAll();
        expect(loadedDances, hasLength(2));
        final owner = loadedDances.firstWhere((d) => d.id == 'd-ok');
        expect(owner.links.single.id, 'l-good');
        expect(owner.links.single.targetDanceId, 'd-target');

        // The database is referentially clean and its FTS index is a perfect
        // 1:1 mirror of `dances`. We compare the ORDERED id multisets (not just
        // row counts): dance_fts.dance_id is an unconstrained FTS column, so a
        // count-only check would pass even if one dance were missing while
        // another had a duplicate row. Comparing sorted id lists catches
        // missing, orphaned, and duplicated FTS rows alike.
        final fkViolations = await db
            .customSelect('PRAGMA foreign_key_check')
            .get();
        expect(fkViolations, isEmpty, reason: 'no dangling FKs after repair');
        final ftsIds =
            (await db
                    .customSelect(
                      'SELECT dance_id FROM dance_fts ORDER BY dance_id',
                    )
                    .get())
                .map((r) => r.read<String>('dance_id'))
                .toList();
        final danceIds =
            (await db.customSelect('SELECT id FROM dances ORDER BY id').get())
                .map((r) => r.read<String>('id'))
                .toList();
        expect(
          ftsIds,
          danceIds,
          reason: 'dance_fts must be an exact 1:1 mirror of dances',
        );

        // The one-shot marker is durably recorded.
        final marker = await db
            .customSelect(
              'SELECT value_json FROM settings WHERE key = ?',
              variables: [Variable.withString(purgeCorruptionRepairDoneKey)],
            )
            .get();
        expect(marker, hasLength(1));
      },
    );

    test('skips the repair when the done-marker is already set', () async {
      final db = CompendiumDatabase(NativeDatabase.memory());
      final repos = CompendiumRepositories(db, contraTaxonomy);
      addTearDown(db.close);

      // Pre-stamp the marker (this first statement also triggers onCreate), so
      // a later corrupt row must be left alone — the sweep runs at most once.
      await db.customStatement(
        'INSERT OR REPLACE INTO settings (key, value_json) VALUES (?, ?)',
        [purgeCorruptionRepairDoneKey, 'true'],
      );
      await repos.programs.create(
        Program(
          id: 'p1',
          title: 'Set',
          slots: [ProgramSlot(id: 's-ok', position: 0, text: 'Waltz')],
          createdAt: DateTime.utc(2026),
          updatedAt: DateTime.utc(2026),
        ),
      );
      await db.customStatement(
        'INSERT INTO program_slots (id, program_id, position, dance_id, text, '
        'is_alt) VALUES (?, ?, ?, NULL, NULL, 0)',
        ['s-bad', 'p1', 1],
      );

      await repos.ensureMigrated();

      final slots = await db
          .customSelect('SELECT id FROM program_slots ORDER BY id')
          .get();
      expect(slots.map((r) => r.read<String>('id')), ['s-bad', 's-ok']);
    });
  });

  group('v20 -> v21 upgrade (drop raw_payload columns and the snapshots '
      'table)', () {
    late Directory dir;
    late String dbPath;

    setUp(() async {
      dir = await Directory.systemTemp.createTemp('compendium_core_mig_v21_');
      dbPath = p.join(dir.path, 'test.sqlite');
      // Copy the checked-in v20 fixture to a temp path (opening mutates it).
      final fixture = File(
        p.join(
          await packageRootPath(),
          'test',
          'storage',
          'fixtures',
          'v20.sqlite',
        ),
      );
      await fixture.copy(dbPath);
    });

    tearDown(() => dir.delete(recursive: true));

    Future<List<String>> columnsOf(CompendiumDatabase db, String table) async {
      final rows = await db
          .customSelect("SELECT name FROM pragma_table_info('$table')")
          .get();
      return [for (final r in rows) r.read<String>('name')];
    }

    test('drift schema version is current after upgrade', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      final repos = CompendiumRepositories(db, contraTaxonomy);
      await repos.ensureMigrated();

      final rows = await db.customSelect('PRAGMA user_version').get();
      expect(rows.single.data.values.first, db.schemaVersion);

      await db.close();
    });

    test('drops raw_payload from both provenance tables', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      final repos = CompendiumRepositories(db, contraTaxonomy);
      await repos.ensureMigrated();

      expect(await columnsOf(db, 'provenance'), isNot(contains('raw_payload')));
      expect(
        await columnsOf(db, 'program_provenance'),
        isNot(contains('raw_payload')),
      );

      await db.close();
    });

    test('preserves every sibling provenance column and its value', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      final repos = CompendiumRepositories(db, contraTaxonomy);
      await repos.ensureMigrated();

      // The rebuild copies surviving columns across by name. A botched column
      // list would silently null one of these rather than fail loudly, so
      // every one is asserted by value, not merely by presence.
      final prov = await db
          .customSelect(
            'SELECT * FROM provenance WHERE dance_id = ?',
            variables: [Variable<String>('dance-1')],
          )
          .getSingle();
      expect(prov.read<String>('source'), 'contradb');
      expect(prov.read<String>('external_id'), '2443');
      expect(prov.read<String>('permission'), 'CC BY-NC-SA 3.0');
      expect(prov.read<String>('license'), 'CC BY-NC-SA 3.0');
      expect(prov.read<String>('source_version'), 'contradb-2026-01');
      // `imported_at` is a sibling column too, and the only non-text one — a
      // rebuild that mis-copied or nulled the timestamp would otherwise pass
      // every assertion above. Stored as unix seconds (2026-01-01T00:00:00Z).
      expect(prov.read<int>('imported_at'), 1767225600);

      final progProv = await db
          .customSelect(
            'SELECT * FROM program_provenance WHERE program_id = ?',
            variables: [Variable<String>('program-1')],
          )
          .getSingle();
      expect(progProv.read<String>('source'), 'callersCompanion');
      expect(progProv.read<String>('external_id'), 'set-42');
      expect(progProv.read<String>('permission'), 'personal use');
      expect(progProv.read<String>('license'), 'unlicensed');
      expect(progProv.read<String>('source_version'), 'cc-usr-1');
      expect(progProv.read<int>('imported_at'), 1767225600);

      await db.close();
    });

    test(
      'the rebuilt provenance row still loads through the repository',
      () async {
        final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
        final repos = CompendiumRepositories(db, contraTaxonomy);
        await repos.ensureMigrated();

        // A table rebuild that lost the primary key or the FK would still pass
        // the column assertions above; loading the dance exercises both.
        final dance = await repos.dances.getById('dance-1');
        expect(dance, isNotNull);
        expect(dance!.provenance, isNotNull);
        expect(dance.provenance!.externalId, '2443');
        expect(dance.provenance!.source, ProvenanceSource.contradb);
        expect(dance.provenance!.importedAt, DateTime.utc(2026));

        await db.close();
      },
    );

    test('drops the snapshots table', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      final repos = CompendiumRepositories(db, contraTaxonomy);
      await repos.ensureMigrated();

      final tables = await db
          .customSelect(
            "SELECT name FROM sqlite_master WHERE type = 'table' "
            "AND name = 'snapshots'",
          )
          .get();
      expect(tables, isEmpty);

      await db.close();
    });

    test('leaves tags.color intact', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      final repos = CompendiumRepositories(db, contraTaxonomy);
      await repos.ensureMigrated();

      // #782 covered both the snapshots table and tags.color; only the former
      // was dropped, because tag colour-coding was wanted and has since been
      // built (#786). This pins that decision: a future cleanup that takes the
      // colour with it fails here rather than silently discarding user data.
      expect(await columnsOf(db, 'tags'), contains('color'));
      final tag = await db
          .customSelect(
            'SELECT color FROM tags WHERE id = ?',
            variables: [Variable<String>('tag-1')],
          )
          .getSingle();
      expect(tag.read<int>('color'), 0xFF2196F3);

      await db.close();
    });

    test(
      'a restored pre-v21 archive keeps its dance and drops the payload',
      () async {
        final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
        final repos = CompendiumRepositories(db, contraTaxonomy);
        await repos.ensureMigrated();

        // Archives written before v21 carry a `rawPayload` key inside each
        // dance's provenance. Rather than hand-rolling that JSON (which risks
        // testing a shape the encoder never produced), encode a real archive
        // through the live encoder and inject the legacy key back into it.
        final encoded = encodeArchive(
          CompendiumArchive(
            exportedAt: DateTime.utc(2026),
            dances: [
              Dance(
                id: 'legacy-1',
                title: 'Legacy Import',
                figures: [
                  Figure(
                    move: 'swing',
                    params: const {'who': 'partners', 'beats': 16},
                  ),
                ],
                createdAt: DateTime.utc(2026),
                updatedAt: DateTime.utc(2026),
                provenance: Provenance(
                  source: ProvenanceSource.contradb,
                  externalId: '999',
                  importedAt: DateTime.utc(2026),
                ),
              ),
            ],
          ),
        );

        final asMap = jsonDecode(encoded) as Map<String, Object?>;
        final danceList = asMap['dances']! as List<Object?>;
        final provenance =
            (danceList.single as Map<String, Object?>)['provenance']!
                as Map<String, Object?>;
        provenance['rawPayload'] = '<html>dropped in v21</html>';
        expect(
          provenance.containsKey('rawPayload'),
          isTrue,
          reason:
              'the legacy key must actually be present, or this test is '
              'asserting nothing',
        );

        // `decodeArchive` ignores unknown keys, so the dance restores intact and
        // the payload is simply not read back — no special-casing, no failure.
        final restored = decodeArchive(jsonEncode(asMap));

        expect(restored.errors, isEmpty);
        expect(restored.archive.dances, hasLength(1));
        expect(restored.archive.dances.single.provenance!.externalId, '999');

        await db.close();
      },
    );
  });

  group('v21 -> v22 upgrade (issue #748 dance_figures.group_idx)', () {
    late Directory dir;
    late String dbPath;

    setUp(() async {
      dir = await Directory.systemTemp.createTemp('compendium_core_mig_v22_');
      dbPath = p.join(dir.path, 'test.sqlite');
      // Copy the checked-in v21 fixture to a temp path (opening mutates it).
      final fixture = File(
        p.join(
          await packageRootPath(),
          'test',
          'storage',
          'fixtures',
          'v21.sqlite',
        ),
      );
      await fixture.copy(dbPath);
    });

    tearDown(() => dir.delete(recursive: true));

    Future<List<String>> columnsOf(CompendiumDatabase db, String table) async {
      final rows = await db
          .customSelect("SELECT name FROM pragma_table_info('$table')")
          .get();
      return [for (final r in rows) r.read<String>('name')];
    }

    test('drift schema version is current after upgrade', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      final repos = CompendiumRepositories(db, contraTaxonomy);
      await repos.ensureMigrated();

      final rows = await db.customSelect('PRAGMA user_version').get();
      expect(rows.single.data.values.first, db.schemaVersion);

      await db.close();
    });

    test('adds the group_idx column to dance_figures', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      final repos = CompendiumRepositories(db, contraTaxonomy);
      await repos.ensureMigrated();

      expect(await columnsOf(db, 'dance_figures'), contains('group_idx'));

      await db.close();
    });

    test('the rebuild repopulates group_idx from figures_json', () async {
      // The migration's `addColumn` gives every existing row the DEFAULT (0);
      // only the scheduled derived rebuild recomputes the real grouping. So a
      // correct result here proves the rebuild ran, not merely the column add:
      // the two concurrent sides of the container share one group_idx, and the
      // trailing top-level figure gets a distinct, higher one.
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      final repos = CompendiumRepositories(db, contraTaxonomy);
      await repos.ensureMigrated();

      final rows = await db
          .customSelect(
            "SELECT move, group_idx FROM dance_figures "
            "WHERE dance_id = 'dance-mw' ORDER BY idx",
          )
          .get();
      final moves = [for (final r in rows) r.read<String>('move')];
      final groups = [for (final r in rows) r.read<int>('group_idx')];
      expect(moves, ['petronella', 'swing', 'long_lines']);
      // Sides of the container share a group; the trailing figure is later.
      expect(groups[0], groups[1]);
      expect(groups[2], greaterThan(groups[1]));

      await db.close();
    });

    test('Then excludes concurrent sides after the migration', () async {
      // End-to-end: against the migrated fixture, a `Then` over the container's
      // two concurrent sides must not match in either direction, while the
      // genuinely sequential `dance-seq` still does.
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      final repos = CompendiumRepositories(db, contraTaxonomy);
      await repos.ensureMigrated();

      expect(
        await repos.dances.search(
          ThenFilter(FigureLeaf('petronella'), FigureLeaf('swing')),
        ),
        ['dance-seq'],
      );
      expect(
        await repos.dances.search(
          ThenFilter(FigureLeaf('swing'), FigureLeaf('petronella')),
        ),
        isEmpty,
      );

      await db.close();
    });
  });

  group('v22 -> v23 upgrade (issue #780 custom_field_defs.shareable)', () {
    late Directory dir;
    late String dbPath;

    setUp(() async {
      dir = await Directory.systemTemp.createTemp('compendium_core_mig_v23_');
      dbPath = p.join(dir.path, 'test.sqlite');
      // Copy the checked-in v22 fixture to a temp path (opening mutates it).
      final fixture = File(
        p.join(
          await packageRootPath(),
          'test',
          'storage',
          'fixtures',
          'v22.sqlite',
        ),
      );
      await fixture.copy(dbPath);
    });

    tearDown(() => dir.delete(recursive: true));

    Future<List<String>> columnsOf(CompendiumDatabase db, String table) async {
      final rows = await db
          .customSelect("SELECT name FROM pragma_table_info('$table')")
          .get();
      return [for (final r in rows) r.read<String>('name')];
    }

    test('drift schema version is current after upgrade', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      addTearDown(db.close);
      final rows = await db.customSelect('PRAGMA user_version').get();
      expect(rows.single.data.values.first, db.schemaVersion);
    });

    test('adds the shareable column to custom_field_defs', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      addTearDown(db.close);
      expect(await columnsOf(db, 'custom_field_defs'), contains('shareable'));
    });

    test('existing custom field row gets shareable = 1 (DEFAULT 1)', () async {
      // The DEFAULT 1 on addColumn means every pre-v23 row comes out shareable.
      // Defaulting to 0 would silently stop those fields from being exported,
      // which is the worse surprise; the correct default preserves today's
      // behaviour. This test verifies the migration's DEFAULT was correct.
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      addTearDown(db.close);

      final rows = await db
          .customSelect(
            "SELECT shareable FROM custom_field_defs WHERE id = 'cf-notes'",
          )
          .get();
      expect(
        rows,
        isNotEmpty,
        reason: 'fixture field cf-notes must be present',
      );
      expect(
        rows.single.read<bool>('shareable'),
        isTrue,
        reason: 'pre-v23 field must default to shareable=true after migration',
      );
    });

    test('existing dance values are preserved after migration', () async {
      // Structural-only migration — no data should be touched.
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      final repos = CompendiumRepositories(db, contraTaxonomy);
      addTearDown(db.close);

      final dance = await repos.dances.getById('dance-v22');
      expect(dance, isNotNull);
      expect(dance!.customFields, hasLength(1));
      expect(dance.customFields.first.fieldId, 'cf-notes');
      expect(dance.customFields.first.value, 'good fun');
    });

    test(
      'v28 rebuild remains scheduled after the v22->v23 migration',
      () async {
        // The v22->v23 step carries no figure data, but opening the old fixture
        // all the way to the current schema must still retain v28's marker.
        final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
        addTearDown(db.close);
        final settings = await db
            .customSelect(
              "SELECT value_json FROM settings "
              "WHERE key = '$derivedRebuildRequiredKey'",
            )
            .get();
        final hasRebuildMarker =
            settings.isNotEmpty &&
            settings.first.read<String>('value_json') == 'true';
        expect(
          hasRebuildMarker,
          isTrue,
          reason: 'the v28 migration must schedule a derived rebuild',
        );
      },
    );
  });

  group('v23 -> v24 upgrade (issue #732 dances.mixer)', () {
    late Directory dir;
    late String dbPath;

    setUp(() async {
      dir = await Directory.systemTemp.createTemp('compendium_core_mig_v24_');
      dbPath = p.join(dir.path, 'test.sqlite');
      // Copy the checked-in v23 fixture to a temp path (opening mutates it).
      final fixture = File(
        p.join(
          await packageRootPath(),
          'test',
          'storage',
          'fixtures',
          'v23.sqlite',
        ),
      );
      await fixture.copy(dbPath);
    });

    tearDown(() => dir.delete(recursive: true));

    Future<List<String>> columnsOf(CompendiumDatabase db, String table) async {
      final rows = await db
          .customSelect("SELECT name FROM pragma_table_info('$table')")
          .get();
      return [for (final r in rows) r.read<String>('name')];
    }

    test('drift schema version is current after upgrade', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      addTearDown(db.close);
      final rows = await db.customSelect('PRAGMA user_version').get();
      expect(rows.single.data.values.first, db.schemaVersion);
    });

    test('adds the mixer column to dances', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      addTearDown(db.close);
      expect(await columnsOf(db, 'dances'), contains('mixer'));
    });

    test('existing dance row gets mixer = 0 (DEFAULT 0)', () async {
      // The DEFAULT 0 on addColumn means every pre-v24 dance comes out a
      // non-mixer. Nothing could be a mixer before v24 (the concept could not
      // be expressed), so the additive default preserves today's behaviour
      // exactly. This test verifies the migration's DEFAULT was correct.
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      addTearDown(db.close);

      final rows = await db
          .customSelect("SELECT mixer FROM dances WHERE id = 'dance-v23'")
          .get();
      expect(
        rows,
        isNotEmpty,
        reason: 'fixture dance dance-v23 must be present',
      );
      expect(
        rows.single.read<bool>('mixer'),
        isFalse,
        reason: 'pre-v24 dance must default to mixer=false after migration',
      );
    });

    test(
      'existing dance is readable through the repository after migration',
      () async {
        // Structural-only migration — no data should be touched, and the dance
        // round-trips with mixer defaulted to false.
        final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
        final repos = CompendiumRepositories(db, contraTaxonomy);
        addTearDown(db.close);

        final dance = await repos.dances.getById('dance-v23');
        expect(dance, isNotNull);
        expect(dance!.title, 'Migration Test Dance');
        expect(dance.mixer, isFalse);
      },
    );

    test(
      'v28 rebuild remains scheduled after the v23->v24 migration',
      () async {
        // The mixer column carries no figure data — the index is untouched.
        final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
        addTearDown(db.close);
        final settings = await db
            .customSelect(
              "SELECT value_json FROM settings "
              "WHERE key = '$derivedRebuildRequiredKey'",
            )
            .get();
        final hasRebuildMarker =
            settings.isNotEmpty &&
            settings.first.read<String>('value_json') == 'true';
        expect(
          hasRebuildMarker,
          isTrue,
          reason: 'the v28 migration must schedule a derived rebuild',
        );
      },
    );
  });

  group('v24 -> v25 upgrade (issue #898 sync timestamps + soft delete)', () {
    late Directory dir;
    late String dbPath;

    /// Sampled just before the migration runs, so any stamp the migration
    /// writes must be at or after it. Used to tell "stamped at migration time"
    /// from "copied out of the fixture", which is the distinction every
    /// back-fill assertion below turns on.
    late int beforeMigration;

    setUp(() async {
      dir = await Directory.systemTemp.createTemp('compendium_core_mig_v25_');
      dbPath = p.join(dir.path, 'test.sqlite');
      // Copy the checked-in v24 fixture to a temp path (opening mutates it).
      final fixture = File(
        p.join(
          await packageRootPath(),
          'test',
          'storage',
          'fixtures',
          'v24.sqlite',
        ),
      );
      await fixture.copy(dbPath);
      beforeMigration = DateTime.now().toUtc().millisecondsSinceEpoch ~/ 1000;
    });

    tearDown(() => dir.delete(recursive: true));

    Future<List<String>> columnsOf(CompendiumDatabase db, String table) async {
      final rows = await db
          .customSelect("SELECT name FROM pragma_table_info('$table')")
          .get();
      return [for (final r in rows) r.read<String>('name')];
    }

    /// Reads one integer column as a nullable int, so a NULL back-fill is
    /// distinguishable from a zero rather than throwing.
    Future<int?> scalar(CompendiumDatabase db, String sql) async {
      final rows = await db.customSelect(sql).get();
      return rows.single.data.values.first as int?;
    }

    test('drift schema version is current after upgrade', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      addTearDown(db.close);
      final rows = await db.customSelect('PRAGMA user_version').get();
      expect(rows.single.data.values.first, db.schemaVersion);
    });

    test('adds all twenty columns across the eight syncable kinds', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      addTearDown(db.close);
      for (final table in const [
        'settings',
        'choreographers',
        'tags',
        'published_sources',
        'custom_field_defs',
        'venues',
      ]) {
        expect(
          await columnsOf(db, table),
          containsAll(['updated_at', 'deleted_at', 'existence_at']),
          reason: '$table must gain all three sync stamps',
        );
      }
      for (final table in const ['dances', 'programs']) {
        expect(
          await columnsOf(db, table),
          containsAll(['updated_at', 'deleted_at', 'existence_at']),
          reason: '$table already had two and must gain existence_at',
        );
      }
    });

    test(
      'every live row shares ONE T0, across tables as well as rows',
      () async {
        // The normative rule is "a single constant T0, identical for every live
        // row" — not "a plausible timestamp per row". The fixture's two live
        // dances were written years apart (2020 and 2026), so a back-fill that
        // copied each row's own `updated_at` would produce two different values
        // here and fail. That is the mutation this test exists to catch.
        final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
        addTearDown(db.close);

        final rows = await db
            .customSelect(
              'SELECT existence_at FROM dances WHERE deleted_at IS NULL '
              'UNION SELECT existence_at FROM programs WHERE deleted_at IS NULL '
              'UNION SELECT existence_at FROM tags '
              'UNION SELECT existence_at FROM choreographers '
              'UNION SELECT existence_at FROM published_sources '
              'UNION SELECT existence_at FROM custom_field_defs '
              'UNION SELECT existence_at FROM venues '
              "UNION SELECT existence_at FROM settings "
              "WHERE key != '$derivedRebuildRequiredKey'",
            )
            .get();
        // UNION dedupes, so one row means one distinct value.
        expect(
          rows,
          hasLength(1),
          reason:
              'every live row across all eight tables must carry the same T0; '
              'got ${[for (final r in rows) r.data.values.first]}',
        );
        final t0 = rows.single.data.values.first as int?;
        expect(t0, isNotNull, reason: 'T0 must not be left NULL');
        expect(
          t0,
          greaterThanOrEqualTo(beforeMigration),
          reason: 'T0 is sampled when the migration runs, not baked in',
        );
      },
    );

    test('an already-tombstoned row keeps its own deleted_at, not T0', () async {
      // The one case where a pre-existing column carries the right meaning.
      // Only dances and programs can exercise it: the other six gain
      // `deleted_at` in this same step, so every row of theirs is live.
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      addTearDown(db.close);

      for (final (table, id) in const [
        ('dances', 'dance-v24-deleted'),
        ('programs', 'program-v24-deleted'),
      ]) {
        final deletedAt = await scalar(
          db,
          "SELECT deleted_at FROM $table WHERE id = '$id'",
        );
        final existenceAt = await scalar(
          db,
          "SELECT existence_at FROM $table WHERE id = '$id'",
        );
        expect(deletedAt, isNotNull, reason: '$id must be tombstoned already');
        expect(
          existenceAt,
          deletedAt,
          reason: '$id must take its own deleted_at, not T0',
        );
        expect(
          existenceAt,
          lessThan(beforeMigration),
          reason:
              'a historical deletion must stay historical — equal to T0 would '
              'mean the deleted_at branch never ran',
        );
      }
    });

    test(
      'existence_at is NOT copied from updated_at where those differ',
      () async {
        // Copying `updated_at` is the natural thing to reach for and it
        // reintroduces the coupling the third column exists to break: a device
        // that edited a live record after another deleted it would outrank the
        // tombstone and resurrect the record on first sync.
        final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
        addTearDown(db.close);

        for (final id in const ['dance-v24-early', 'dance-v24-late']) {
          final updatedAt = await scalar(
            db,
            "SELECT updated_at FROM dances WHERE id = '$id'",
          );
          final existenceAt = await scalar(
            db,
            "SELECT existence_at FROM dances WHERE id = '$id'",
          );
          expect(
            existenceAt,
            isNot(updatedAt),
            reason: '$id: existence_at must not be back-filled from updated_at',
          );
        }
        // And the fixture really does make them differ, so the assertion above
        // has something to bite on rather than passing vacuously.
        final early = await scalar(
          db,
          "SELECT updated_at FROM dances WHERE id = 'dance-v24-early'",
        );
        final late_ = await scalar(
          db,
          "SELECT updated_at FROM dances WHERE id = 'dance-v24-late'",
        );
        expect(
          early,
          isNot(late_),
          reason: 'fixture must hold two live dances with different updated_at',
        );
      },
    );

    test('dances and programs keep their own updated_at untouched', () async {
      // Only the six tables that gained `updated_at` get it stamped. Rewriting
      // a dance's `updated_at` would tell every peer its content had changed
      // when nothing did.
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      addTearDown(db.close);
      expect(
        await scalar(
          db,
          "SELECT updated_at FROM dances WHERE id = 'dance-v24-early'",
        ),
        DateTime.utc(2020, 3, 4, 5, 6, 7).millisecondsSinceEpoch ~/ 1000,
      );
      expect(
        await scalar(
          db,
          "SELECT updated_at FROM programs WHERE id = 'program-v24-live'",
        ),
        DateTime.utc(2026, 1, 1).millisecondsSinceEpoch ~/ 1000,
      );
    });

    test(
      'the six new tables get updated_at stamped at migration time',
      () async {
        final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
        addTearDown(db.close);
        for (final (table, keyCol, key) in const [
          ('tags', 'id', 'tag-v24'),
          ('choreographers', 'id', 'chor-v24'),
          ('published_sources', 'id', 'src-v24'),
          ('custom_field_defs', 'id', 'cfd-v24'),
          ('venues', 'id', 'venue-v24'),
          ('settings', 'key', 'migration_setting'),
        ]) {
          final updatedAt = await scalar(
            db,
            "SELECT updated_at FROM $table WHERE $keyCol = '$key'",
          );
          expect(updatedAt, isNotNull, reason: '$table.updated_at must be set');
          expect(
            updatedAt,
            greaterThanOrEqualTo(beforeMigration),
            reason: '$table.updated_at is stamped when the migration runs',
          );
          expect(
            await scalar(
              db,
              "SELECT deleted_at FROM $table WHERE $keyCol = '$key'",
            ),
            isNull,
            reason: '$table row was live before the migration and stays live',
          );
        }
      },
    );

    test(
      'pre-existing data survives and still loads through the repositories',
      () async {
        final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
        final repos = CompendiumRepositories(db, contraTaxonomy);
        addTearDown(db.close);

        final dance = await repos.dances.getById('dance-v24-early');
        expect(dance, isNotNull);
        expect(dance!.title, 'Early Dance');
        // The join rows through the newly soft-deletable parents still resolve:
        // both parents are live, so filtering must not have dropped them.
        expect(dance.tagIds, ['tag-v24']);
        expect(dance.authorIds, ['chor-v24']);

        expect((await repos.tags.getById('tag-v24'))!.name, 'Migration Tag');
        expect(
          (await repos.choreographers.getById('chor-v24'))!.name,
          'Migration Author',
        );
        expect(
          (await repos.publishedSources.getById('src-v24'))!.title,
          'Migration Source',
        );
        expect(
          (await repos.customFieldDefs.getById('cfd-v24'))!.key,
          'migration_field',
        );
        expect(
          (await repos.venues.getById('venue-v24'))!.name,
          'Migration Hall',
        );
        expect(await repos.settings.get('migration_setting'), 'kept');

        // The tombstoned dance is still tombstoned, and still hidden.
        expect(await repos.dances.getById('dance-v24-deleted'), isNull);
        expect(await repos.programs.getById('program-v24-deleted'), isNull);
      },
    );

    test('v28 rebuild remains scheduled after the v24->v25 migration', () async {
      // Twenty timestamp columns carry no figure data — the index is untouched.
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      addTearDown(db.close);
      final settings = await db
          .customSelect(
            "SELECT value_json FROM settings "
            "WHERE key = '$derivedRebuildRequiredKey'",
          )
          .get();
      final hasRebuildMarker =
          settings.isNotEmpty &&
          settings.first.read<String>('value_json') == 'true';
      expect(
        hasRebuildMarker,
        isTrue,
        reason: 'the v28 migration must schedule a derived rebuild',
      );
    });
  });

  group('v25 -> v26 upgrade (issue #899 venue provenance for dedupe)', () {
    late Directory dir;
    late String dbPath;

    setUp(() async {
      dir = await Directory.systemTemp.createTemp('compendium_core_mig_v26_');
      dbPath = p.join(dir.path, 'test.sqlite');
      // Copy the checked-in v25 fixture to a temp path (opening mutates it).
      final fixture = File(
        p.join(
          await packageRootPath(),
          'test',
          'storage',
          'fixtures',
          'v25.sqlite',
        ),
      );
      await fixture.copy(dbPath);
    });

    tearDown(() => dir.delete(recursive: true));

    test('drift schema version is current after upgrade', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      addTearDown(db.close);
      await db.customSelect('SELECT 1').get();
      final version = await db
          .customSelect('PRAGMA user_version')
          .map((r) => r.data)
          .get();
      expect(version.first.values.first, kCompendiumSchemaVersion);
    });

    test('creates the venue_provenance table', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      addTearDown(db.close);
      await db.customSelect('SELECT 1').get();
      final tables = await db
          .customSelect(
            "SELECT name FROM sqlite_master WHERE type='table' "
            "AND name='venue_provenance'",
          )
          .get();
      expect(tables, hasLength(1), reason: 'venue_provenance must exist');
    });

    test('existing venue data survives the migration', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      final repos = CompendiumRepositories(db, contraTaxonomy);
      addTearDown(db.close);
      final venue = await repos.venues.getById('venue-v25');
      expect(venue, isNotNull);
      expect(venue!.name, 'Migration Hall v25');
    });

    test('venue_provenance starts empty (no back-fill)', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      addTearDown(db.close);
      await db.customSelect('SELECT 1').get();
      final rows = await db
          .customSelect('SELECT COUNT(*) AS c FROM venue_provenance')
          .map((r) => r.read<int>('c'))
          .get();
      expect(
        rows.first,
        0,
        reason: 'v25->v26 migration must not back-fill venue_provenance',
      );
    });

    test(
      'venue_provenance enforces unique non-null source/external-id pairs',
      () async {
        final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
        addTearDown(db.close);
        await db.customSelect('SELECT 1').get();

        Future<void> insertVenue(String id) {
          return db
              .into(db.venues)
              .insert(VenuesCompanion.insert(id: id, name: id));
        }

        Future<void> insertVenueProvenance(String venueId, String? externalId) {
          return db
              .into(db.venueProvenance)
              .insert(
                VenueProvenanceCompanion.insert(
                  venueId: venueId,
                  source: ProvenanceSource.json,
                  externalId: Value(externalId),
                  importedAt: DateTime.utc(2026, 1, 1),
                ),
              );
        }

        await insertVenue('venue-a');
        await insertVenue('venue-b');
        await insertVenueProvenance('venue-a', 'shared-venue-1');

        await expectLater(
          insertVenueProvenance('venue-b', 'shared-venue-1'),
          throwsA(isA<SqliteException>()),
        );
      },
    );

    test('venue_provenance still allows multiple null external ids', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      addTearDown(db.close);
      await db.customSelect('SELECT 1').get();

      await db
          .into(db.venues)
          .insert(VenuesCompanion.insert(id: 'venue-a', name: 'venue-a'));
      await db
          .into(db.venues)
          .insert(VenuesCompanion.insert(id: 'venue-b', name: 'venue-b'));

      await db
          .into(db.venueProvenance)
          .insert(
            VenueProvenanceCompanion.insert(
              venueId: 'venue-a',
              source: ProvenanceSource.json,
              externalId: const Value(null),
              importedAt: DateTime.utc(2026, 1, 1),
            ),
          );
      await db
          .into(db.venueProvenance)
          .insert(
            VenueProvenanceCompanion.insert(
              venueId: 'venue-b',
              source: ProvenanceSource.json,
              externalId: const Value(null),
              importedAt: DateTime.utc(2026, 1, 1),
            ),
          );

      final rows = await db.select(db.venueProvenance).get();
      expect(rows, hasLength(2));
    });

    test(
      'v28 rebuild remains scheduled after the v25->v26 migration',
      () async {
        // A new table with no figure data — the index is untouched.
        final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
        addTearDown(db.close);
        final settings = await db
            .customSelect(
              "SELECT value_json FROM settings "
              "WHERE key = '$derivedRebuildRequiredKey'",
            )
            .get();
        final hasRebuildMarker =
            settings.isNotEmpty &&
            settings.first.read<String>('value_json') == 'true';
        expect(
          hasRebuildMarker,
          isTrue,
          reason: 'the v28 migration must schedule a derived rebuild',
        );
      },
    );
  });

  group('v26 -> v27 upgrade (issue #862 published collection history)', () {
    late Directory dir;
    late String dbPath;

    setUp(() async {
      dir = await Directory.systemTemp.createTemp('compendium_core_mig_v27_');
      dbPath = p.join(dir.path, 'test.sqlite');
      final fixture = File(
        p.join(
          await packageRootPath(),
          'test',
          'storage',
          'fixtures',
          'v26.sqlite',
        ),
      );
      await fixture.copy(dbPath);
    });

    tearDown(() => dir.delete(recursive: true));

    test('creates the idempotent collection import event table', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      addTearDown(db.close);
      await db.customSelect('SELECT 1').get();
      final tables = await db
          .customSelect(
            "SELECT name FROM sqlite_master WHERE type='table' "
            "AND name='collection_import_events'",
          )
          .get();
      expect(tables, hasLength(1));

      final event = CollectionImportEvent(
        collectionId: 'book',
        version: 'v1',
        archiveDigest: 'sha256:digest',
        importedAt: DateTime.utc(2026, 8, 20),
      );
      final events = CollectionImportEventRepository(db);
      await events.record(event);
      await events.record(event);
      expect(await events.listAll(), hasLength(1));
    });
  });

  group('v27 -> v28 upgrade (scoped collection search indexes)', () {
    late Directory dir;
    late String dbPath;

    setUp(() async {
      dir = await Directory.systemTemp.createTemp('compendium_core_mig_v28_');
      dbPath = p.join(dir.path, 'test.sqlite');
      final fixture = File(
        p.join(
          await packageRootPath(),
          'test',
          'storage',
          'fixtures',
          'v27.sqlite',
        ),
      );
      await fixture.copy(dbPath);
    });

    tearDown(() => dir.delete(recursive: true));

    test('preserves fixture data and rebuilds both search indexes', () async {
      final db = CompendiumDatabase(NativeDatabase(File(dbPath)));
      final repos = CompendiumRepositories(db, contraTaxonomy);
      addTearDown(db.close);

      await repos.ensureMigrated();

      final dances = await repos.dances.listAll();
      expect(dances, isNotEmpty);
      expect(dances.map((dance) => dance.id), contains('dance-1'));

      final indexTables = await db
          .customSelect(
            "SELECT name FROM sqlite_master "
            "WHERE type = 'table' AND name IN (?, ?)",
            variables: [
              Variable.withString('dance_fts'),
              Variable.withString('dance_substring_fts'),
            ],
          )
          .get();
      expect(indexTables, hasLength(2));

      final danceIds =
          (await db.customSelect('SELECT id FROM dances ORDER BY id').get())
              .map((row) => row.read<String>('id'))
              .toList();
      for (final table in ['dance_fts', 'dance_substring_fts']) {
        final indexedIds =
            (await db
                    .customSelect(
                      'SELECT dance_id FROM $table ORDER BY dance_id',
                    )
                    .get())
                .map((row) => row.read<String>('dance_id'))
                .toList();
        expect(indexedIds, danceIds, reason: '$table must mirror dances');
      }

      final marker = await db
          .customSelect(
            'SELECT value_json FROM settings WHERE key = ?',
            variables: [Variable.withString(derivedRebuildRequiredKey)],
          )
          .get();
      expect(marker, isEmpty);
    });
  });

  group('v29 -> v30 upgrade (normalisation skip minimization)', () {
    test('drops target snapshots while preserving skip identities', () async {
      final raw = sqlite3.sqlite3.openInMemory();
      final historical = GeneratedHelper().databaseForVersion(
        NativeDatabase.opened(raw, closeUnderlyingOnClose: false),
        29,
      );
      await historical.customSelect('SELECT 1').get();
      await historical.customStatement(
        'INSERT INTO normalisation_skips '
        '(table_name, column_name, record_id, target_value) VALUES (?, ?, ?, ?)',
        ['tags', 'name', 't1', 'café'],
      );
      await historical.close();

      final db = CompendiumDatabase(
        NativeDatabase.opened(raw, closeUnderlyingOnClose: false),
      );
      addTearDown(() async {
        await db.close();
        raw.close();
      });
      await db.customSelect('SELECT 1').get();

      final columns = await db
          .customSelect(
            "SELECT name FROM pragma_table_info('normalisation_skips')",
          )
          .get();
      expect(
        [for (final row in columns) row.read<String>('name')],
        ['table_name', 'column_name', 'record_id'],
      );
      final rows = await db
          .customSelect(
            'SELECT table_name, column_name, record_id FROM '
            'normalisation_skips',
          )
          .get();
      expect(rows.single.data, {
        'table_name': 'tags',
        'column_name': 'name',
        'record_id': 't1',
      });
    });
  });

  group('v30 -> v31 upgrade (transitive related-dance links)', () {
    test('adds a false-by-default transitive marker', () async {
      final raw = sqlite3.sqlite3.openInMemory();
      final historical = GeneratedHelper().databaseForVersion(
        NativeDatabase.opened(raw, closeUnderlyingOnClose: false),
        30,
      );
      await historical.customSelect('SELECT 1').get();
      await historical.customStatement(
        'INSERT INTO dance_links '
        '(id, dance_id, kind, target_dance_id, label) VALUES (?, ?, ?, ?, ?)',
        ['link-1', 'dance-1', 'relatedDance', 'dance-2', 'legacy note'],
      );
      await historical.close();

      final db = CompendiumDatabase(
        NativeDatabase.opened(raw, closeUnderlyingOnClose: false),
      );
      addTearDown(() async {
        await db.close();
        raw.close();
      });
      await db.customSelect('SELECT 1').get();

      final columns = await db
          .customSelect("SELECT name FROM pragma_table_info('dance_links')")
          .get();
      expect([
        for (final row in columns) row.read<String>('name'),
      ], contains('transitive'));
      final row = await db
          .customSelect(
            'SELECT transitive FROM dance_links WHERE id = ?',
            variables: [Variable.withString('link-1')],
          )
          .getSingle();
      expect(row.read<int>('transitive'), 0);
    });
  });
}

/// A [CompendiumRepositories] whose derived-index rebuild throws on its first
/// invocation and succeeds thereafter — used to prove [ensureMigrated] retries
/// after a transient failure rather than caching it.
class _FailingOnceRepositories extends CompendiumRepositories {
  _FailingOnceRepositories(super.db, super.taxonomy);

  int rebuildAttempts = 0;

  @override
  Future<void> runDerivedRebuild({
    DerivedRebuildProgressCallback? onProgress,
  }) async {
    rebuildAttempts++;
    if (rebuildAttempts == 1) {
      throw StateError('injected rebuild failure');
    }
    await super.runDerivedRebuild(onProgress: onProgress);
  }
}

/// Counts [runDerivedRebuild] calls without interfering with the real rebuild.
class _CountingRepositories extends CompendiumRepositories {
  _CountingRepositories(super.db, super.taxonomy);

  int rebuildAttempts = 0;

  @override
  Future<void> runDerivedRebuild({
    DerivedRebuildProgressCallback? onProgress,
  }) async {
    rebuildAttempts++;
    await super.runDerivedRebuild(onProgress: onProgress);
  }
}
